from pathlib import Path
p=Path('editor/Medieval_Battlefield_Editor_v4.py')
s=p.read_text(encoding='utf-8')
start=s.index('    def draw_line_obj(self,o):')
end=s.index('    def draw_obj(self,o):',start)
new='''    def draw_line_obj(self,o):\n        p=self.pts(o['points']);wd=o.get('width',25)*self.scale\n        if o['kind']=='river':\n            self.canvas.create_line(*p,fill='#4b4238',width=max(8,int(wd+32*self.scale)),smooth=True,capstyle='round')\n            self.canvas.create_line(*p,fill='#4fa8a2',width=max(5,int(wd)),smooth=True,capstyle='round')\n            self.canvas.create_line(*p,fill='#8ccbc1',width=max(1,int(3*self.scale)),smooth=True,capstyle='round')\n            return\n        rt=o.get('road_type','Просёлочная')\n        colors={'Просёлочная':('#b79a70','#dbc79f'),'Мощенная':('#756b5d','#b9ad96'),'Брусчаточная':('#8b7b67','#c5b69a')}\n        surf,detail=colors.get(rt,colors['Просёлочная'])\n        self.canvas.create_line(*p,fill=surf,width=max(3,int(wd)),smooth=True,capstyle='round')\n        dash=(2,5) if rt=='Брусчаточная' else (7,6) if rt=='Мощенная' else ()\n        self.canvas.create_line(*p,fill=detail,width=max(1,int(wd*.13)),smooth=True,capstyle='round',dash=dash)\n\n    def draw_road_network_underlay(self):\n        roads=[o for o in self.objects if o.get('kind')=='road']\n        for o in roads:\n            p=self.pts(o.get('points',[]));wd=o.get('width',25)*self.scale\n            self.canvas.create_line(*p,fill='#4a3b2d',width=max(5,int(wd+10*self.scale)),smooth=True,capstyle='round')\n\n    def draw_road_junctions(self):\n        roads=[o for o in self.objects if o.get('kind')=='road']\n        for i,a in enumerate(roads):\n            for b in roads[i+1:]:\n                ra=max(3,a.get('width',25)*self.scale*.50);rb=max(3,b.get('width',25)*self.scale*.50)\n                radius=max(ra,rb)+3*self.scale\n                for sa,sb in self.line_segments(a):\n                    for sc,sd in self.line_segments(b):\n                        q=self.seg_intersection(sa,sb,sc,sd)\n                        if q:\n                            x,y=self.world_to_screen(*q)\n                            self.canvas.create_oval(x-radius,y-radius,x+radius,y+radius,fill='#9b8567',outline='')\n                            self.canvas.create_oval(x-radius*.78,y-radius*.78,x+radius*.78,y+radius*.78,fill='#b7a07e',outline='')\n\n'''.replace("\\n","\n")
s=s[:start]+new+s[end:]
needle='        self.draw_junctions()\n        for o in self.objects:'
replacement='        self.draw_road_network_underlay()\n        for o in self.objects:\n            if o.get(\'kind\')==\'road\' and self._bbox_visible(o,rect): self.draw_line_obj(o)\n        self.draw_road_junctions()\n        self.draw_junctions()\n        for o in self.objects:'
if needle in s:s=s.replace(needle,replacement)
s=s.replace("return {'version':6,","return {'version':7,")
p.write_text(s,encoding='utf-8')