from pathlib import Path
p=Path('editor/Medieval_Battlefield_Editor_v4.py')
s=p.read_text(encoding='utf-8')
start=s.index('    def draw_line_obj(self,o):')
end=s.index('    def draw_obj(self,o):',start)
new='''    def road_nodes(self):\n        roads=[o for o in self.objects if o.get('kind')=='road']\n        nodes=[]\n        for o in roads:\n            pts=o.get('points',[])\n            for pt in ([pts[0],pts[-1]] if len(pts)>1 else pts): nodes.append({'p':pt,'roads':[o]})\n        # Build shared junction nodes from endpoints and intersections.\n        for i,a in enumerate(roads):\n            for b in roads[i+1:]:\n                for sa,sb in self.line_segments(a):\n                    for sc,sd in self.line_segments(b):\n                        q=self.seg_intersection(sa,sb,sc,sd)\n                        if q:\n                            n=min(nodes,key=lambda n:(n['p'][0]-q[0])**2+(n['p'][1]-q[1])**2) if nodes else None\n                            if n and (n['p'][0]-q[0])**2+(n['p'][1]-q[1])**2<90**2:\n                                n['roads']=list({id(x):x for x in n['roads']+[a,b]}.values())\n                            else:nodes.append({'p':q,'roads':[a,b]})\n        return nodes\n\n    def draw_line_obj(self,o):\n        p=self.pts(o['points']);wd=o.get('width',25)*self.scale\n        if o['kind']=='river':\n            self.canvas.create_line(*p,fill='#4b4238',width=max(8,int(wd+32*self.scale)),smooth=True,capstyle='round')\n            self.canvas.create_line(*p,fill='#4fa8a2',width=max(5,int(wd)),smooth=True,capstyle='round')\n            self.canvas.create_line(*p,fill='#8ccbc1',width=max(1,int(3*self.scale)),smooth=True,capstyle='round')\n            return\n        rt=o.get('road_type','Просёлочная')\n        colors={'Просёлочная':('#b79a70','#dbc79f'),'Мощенная':('#756b5d','#b9ad96'),'Брусчаточная':('#8b7b67','#c5b69a')}\n        surf,detail=colors.get(rt,colors['Просёлочная'])\n        self.canvas.create_line(*p,fill=surf,width=max(3,int(wd)),smooth=True,capstyle='round')\n        dash=(2,5) if rt=='Брусчаточная' else (7,6) if rt=='Мощенная' else ()\n        self.canvas.create_line(*p,fill=detail,width=max(1,int(wd*.13)),smooth=True,capstyle='round',dash=dash)\n\n    def draw_road_network(self):\n        roads=[o for o in self.objects if o.get('kind')=='road']\n        if not roads:return\n        # One continuous under-surface makes connected segments visually one road.\n        for o in roads:\n            p=self.pts(o.get('points',[]));wd=o.get('width',25)*self.scale\n            self.canvas.create_line(*p,fill='#4a3b2d',width=max(5,int(wd+10*self.scale)),smooth=True,capstyle='round')\n        for o in roads:self.draw_line_obj(o)\n        for n in self.road_nodes():\n            x,y=self.world_to_screen(*n['p']);rad=max(5,max((r.get('width',25) for r in n['roads']))*self.scale*.55)\n            rt=n['roads'][0].get('road_type','Просёлочная')\n            fill={'Просёлочная':'#b79a70','Мощенная':'#756b5d','Брусчаточная':'#8b7b67'}.get(rt,'#b79a70')\n            self.canvas.create_oval(x-rad,y-rad,x+rad,y+rad,fill=fill,outline='')\n\n'''.replace("\\n","\n")
s=s[:start]+new+s[end:]
old="        self.draw_road_network_underlay()\n        for o in self.objects:\n            if o.get('kind')=='road' and self._bbox_visible(o,rect): self.draw_line_obj(o)\n        self.draw_road_junctions()"
if old in s:s=s.replace(old,"        self.draw_road_network()")
s=s.replace("return {'version':7,","return {'version':8,")
p.write_text(s,encoding='utf-8')